repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.9.2
    hooks:
      - id: ansible-lint
        files: ^(?!\.).*\.(yaml|yml)$
        verbose: true
        args: ["-p", "./"]
