---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    verify:
      wireguard_ui_version: "v0.6.2"
      wireguard_ui_os: "linux"
      wireguard_ui_architecture: "arm64"
  tasks:
    - name: Print env
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ ansible_version }}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family }}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Set facts
      ansible.builtin.set_fact:
        archive_name: "wireguard-ui-{{ verify.wireguard_ui_version }}-{{ verify.wireguard_ui_os }}-{{ verify.wireguard_ui_architecture }}.tar.gz"

    - name: Check if wireguard-ui is installed
      ansible.builtin.stat:
        path: /usr/local/bin/wireguard-ui
      register: wireguard_ui_stat_result
      failed_when: not wireguard_ui_stat_result.stat.exists

    - name: Check that archive isn't present anymore
      ansible.builtin.stat:
        path: "/tmp/{{ archive_name }}"
      register: wireguard_ui_archive_stat_result
      failed_when: wireguard_ui_archive_stat_result.stat.exists
