name: galaxy-publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/ansible-galaxy-publish.yaml@f78634d1cc51dd41e41a0901e75ded32775e6fc7 # 2.0.29
    secrets:
      galaxy-api-token: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
