name: galaxy-publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/ansible-galaxy-publish.yaml@d1dffd228d24d880ae13b2b4c45d322f28848fea # 2.0.31
    secrets:
      galaxy-api-token: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
