name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.0

      - name: install test dependencies
        run: pip3 install ansible ansible-lint yamllint molecule molecule-plugins[podman]

      - name: run molecule test
        run: molecule test
